name: Build Fabric & Forge Mods

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [fabric, forge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build ${{ matrix.platform }} mod
        run: ./gradlew :${{ matrix.platform }}:build --no-daemon

      - name: Find main jars for ${{ matrix.platform }}
        id: find_jars
        run: |
          echo "Finding main jars in ${{ matrix.platform }}/build/libs"
          JARS=$(find ${{ matrix.platform }}/build/libs/ -name '*.jar' | grep -vE '(-dev-shadow|-sources)\.jar$' | tr '\n' ' ')
          echo "Found jars: $JARS"
          echo "files=$JARS" >> $GITHUB_OUTPUT

      - name: Upload main jars for ${{ matrix.platform }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-main-jars
          path: ${{ steps.find_jars.outputs.files }}
